services:
  movies:
    image: movies
    ports:
      - 8080:3000
    container_name: movies
    networks:
      - movies
  server:
    image: server
    container_name: server
    ports:
      - 5000:5000
    volumes:
      - C:/Users/laste/Downloads:/movies
    networks:
      - movies
    environment:
      - DIRECTORY_PATH=/movies


networks:
  movies:
    driver: bridge